### CONFIGURATION
config:
  # Shell used to execute commands. Omit to use user default (`$SHELL`).
  shell:      'sh'
  # Execute command in background.
  background: false
  # Specify stdout for commands. Inherits parent stdout by default.
  #stdout:     '~/.cache/quickeys/stdout'
  # Specify stderr for commands. Inherits parent stderr by default.
  #stderr:     '~/.cache/quickeys/stderr'

### CONSTANTS
constants:
  terminal: 'alacritty'
  shell:    'bash -c'
  browser:  'firefox'
  editor:   'nvim'

### KEYBINDINGS
##  Here you can define your keybindings.
##  The keystroke combination to activate them is their key,
##  and their value is the shell script that will be executed.
keybindings:
  ## BASE
  q:  'true'
  f:  'false'

  ec: "echo hi"
  se: '@{shell} "echo HI"'

  sl: "sleep 30s"
  ye: "yes"

  ## OPEN applications
  ot: '@terminal'
  of: '@browser --new-window'
