### CONFIGURATION
config:
  # Execute command in background.
  exec-background: true

### CONSTANTS
constants:
  terminal: 'alacritty'
  browser:  'firefox'
  editor:   'nvim'

### KEYBINDINGS
##  Here you can define your keybindings.
##  The keystroke combination to activate them is their key,
##  and their value is the shell script that will be executed.
keybindings:
  ## BASE
  q:  'true'

  ## OPEN applications
  ot: '@terminal'
  of: '@browser --new-window'
